package.json, vue/index.d.ts, vue/index.js, yarn.lock
- Update Vue to 3.0.8
- Simplify types
- Simplify docs examples
=> A small update of Vue

create-router/index.js, create-router/index.test.ts, package.json
Whe hash becomes empty hashchange event is not dispatched for some reason
=> Dispatch artificial hashchange when hash is removed

package.json
Looks like we need it at least for Vite.
=> build: add vue and react to package.exports

README.md, create-router/index.d.ts, create-router/index.test.ts
=> test(create-router): add mising test and update docs

README.md, create-router/errors.ts, create-router/index.d.ts, create-router/index.js, create-router/index.test.ts, create-router/types.ts, index.d.ts, index.js, package.json
=> feat(create-router): add redirectPage method to replace current state in history

package.json, yarn.lock
It just works. No breaking changes.
=> build(deps): bump `vue` to 3.1.1

package.json, vue/index.d.ts, vue/index.js
It can wait for the next release.
=> Reduce size and fix docs of Vue part

vue/index.js, vue/production.test.js
=> feat(vue): readonly state for non-production

package.json, yarn.lock
=> Update `vue` to 3.2.1

create-map/errors.ts, create-map/index.d.ts
* Fixed `setKey` and `notify`
* Also fixed `value` in `setKey`
=> fix: union type in createMap

create-map/index.d.ts
=> fix: 🧪 add generic constrain to Get

vue/index.test.ts
This test easily explains why we use `triggerRef` in `useStore` composable.
=> test(vue): renders map store

README.md
This commit will remove deprecated example with **update** function
=> Fix Readme example

README.md, deprecated/index.d.ts, map/index.d.ts
=> Docs update

README.md, lifecycle/index.d.ts, lifecycle/index.js, lifecycle/index.test.ts
=> Support `shared` object for `onMount`, Write more tests and Update docs

atom/errors.ts, atom/index.d.ts, atom/index.test.ts, test/helpers.ts
=> Making an atom without an initial value should return possibly undefined

README.md
- Follow modern Vue conventions
- Remove indentations from <script> block
- Put script block before template
=> Update Vue example to use script setup

CHANGELOG.md, action/index.js, atom/index.js, index.d.ts, index.js, lifecycle/index.d.ts, lifecycle/index.test.ts, package.json
- Added support for synchronous action for `onAction`
- Added `actionId` export
- Improved docs
=> Some improvements for `@nanostores/logger`

atom/index.js, package.json
```
size-limit:
Atom: - 16 B
All: - 12 B
```
=> Size optimizations from autosubscribe branch

README.md, computed/index.d.ts, computed/index.js, computed/index.test.ts, index.d.ts, index.js, package.json
Reverts nanostores/nanostores#224
=> Revert "Adding batch-mode for `computed`"

action/index.d.ts, action/index.test.ts, atom/errors.ts, computed/index.test.ts, deep-map/index.test.ts, test/benchmark.js
ported from https://github.com/nanostores/nanostores/pull/221
=> Variables in tests & jsdocs match $ prefix convention

deep-map/index.d.ts, deep-map/index.js, deep-map/path.d.ts, deep-map/path.js, index.d.ts, index.js
I have copied some things in the declaration in the comment from the `setPath` function. 
#295
=> Export `setByKey` function

computed/errors.ts, computed/index.d.ts, task/types.ts
=> Fix types for computed with async task

README.md
I guess that example was planned this way
=> (Probably) Fix typo

README.md
Thanks for the awesome library! I'm using nanostores in my projects, including for managing query strings and search parameters. Just wanted to share this in case it's helpful to anyone with a similar need!
=> docs: add nanostores-qs
