create-map/errors.ts
create-map/index.d.ts

Details: https://stackoverflow.com/a/61685380/6540091
This should not lead to any additional errors, because `changedKey` is usually used in comparisons.

Allow keys of every union part to be used in `changedKey`

---

README.md

NextJS 11.1 added a flag to enable their (currently experimetal) ESM support. This option is available as a preview for NextJS 12, which will support ESM out of the box.

add note about nextjs11.1 workaround

---

atom/errors.ts
atom/index.d.ts
map/index.d.ts

Add type for notify function

---

index.d.ts

Since we uses it in types of devtools and logger

types(map-template): export `AnySyncTemplate `

---

map/index.d.ts

* The bug that we found in ts-essentials – https://github.com/krzkaczor/ts-essentials/issues/278#issuecomment-998235314
* The explanation in the release – https://devblogs.microsoft.com/typescript/announcing-typescript-2-9-2/#support-for-symbols-and-numeric-literals-in-keyof-and-mapped-object-types
That's the way how to tolerate `keyofStringsOnly` option in TypeScript

fix: 🔄 PropertyKey => KeyofBase

---

README.md

There is no nextjs section so the link should be removed

docs: remove obsolete link

---

atom/index.d.ts
atom/index.js
computed/index.js
computed/index.test.ts

fix: store.off() can cause listeners to be out of order
fixes https://github.com/nanostores/nanostores/issues/101

notify: use a listenerQueue for breadth-first instead of depth-first notification propagation

---

README.md

The old link went to the top of the page because the id of the header was changed. This PR resolves that.

Update Svelte store contract link

---

atom/index.d.ts
atom/index.test.ts

Fixes [issues/130](https://github.com/nanostores/nanostores/issues/130)

ReadonlyIfObject: Primitive opaque types are not Readonly

---

README.md

@ai 
I added a section in the readme for the lit integration we have been talking about in #95. It only covers the most simple way to use it with the reactive controllers directly and I just used the example from the Solid integration above.
However, I don't think we should merge this just yet. The code is not published to npm (I don't think I can publish to the nanostores npm space?) and the lit integration repository is still private in the nanostores GitHub organization.

Added lit docs

---

README.md
atom/index.js
computed/index.js
computed/index.test.ts
lifecycle/index.js
package.json

Let's consider following example: 
```
let a = atom(0)
let b = computed(a, v => v)
let c = computed(b, v => v)
let d = computed([b, c], (b, c) => `${b} ${c}`)
d.subscribe((v) => {
console.log('d', v);
});
```
The example above has following structure: `A -> B, B -> C, BC -> D`
It turns out that the problem is caused by the order in which listeners are added to the `b` store. The order of listeners follows the order of stores, passed to `d`. Since in the array `[b, c]` `b` comes first, `d` subscribes to `b`, then to `c`, and only then `c` subscribes to `b`. So `b` will notify `d` before `c`. Passing `[c, b]` solves the problem.
Letting users to manage the order of stores might not be the best option, since the relations between stores can be tricky and will cause bugs.
In my proposed …

Introduce level property to allow sorting of stores in computed

---

listen-keys/errors.ts
map/errors.ts
map/index.d.ts

The basic idea is quite simple:
1. we establish a contract, that anything that complies with the signature `{ setKey: (key: any, value: any) => void }` can in fact work with `listenKeys`
2. we make a new generic helper that infers possible key values based on this contract. This is used in `listenKeys` and can then be imported in react/preact/solid/vue types as well.
This will play well with nanoform and, possibly, other custom map-based implementations.

Updating TS signatures for map-alike stores

---

action/index.test.ts
atom/index.js
atom/index.test.ts
package.json

React useSyncExternalStore triggers rerenders only when value is not referentially equal to previous one.
Here updated atom to not notify subscriptions when new value is same.
This change will let as avoid additional checks in user land and rely more on store.subscribe in non-react logic.

Check referential equality before notifying

---

atom/index.js
package.json

Found the source of change here https://github.com/nanostores/nanostores/commit/242d2b123ba4ccb7f11687fae40f70a3878b8bcc
Though back then listeners were called in the same loop. Now listeners are called when iterating over listenerQueue which makes copying unnecessary.

Avoid copying listeners

---

README.md

Simple docs typo fix: The example is supposed to be for `Store#subscribe()`, not `.listen()`.

Fix README typo: .listen() -> .subscribe()

---

atom/errors.ts
atom/index.d.ts
atom/index.js
computed/index.js
package.json

`store.notify()` was used to enforce update when no value is changed though this case is not valid in react which checks referential equality before update.
Here remove store.notify from types and dropped notifyId which was used to enforce recomputing of dependent computed stores.

Drop notifyId and remove store.notify from public api

---

action/index.d.ts

JsDocs for `action` seems to be out of sync with the example provided in main README - first argument of callback is the `store`.

docs(action): update JsDocs example for "action"

---

computed/index.js
computed/index.test.ts
package.json

Ref https://github.com/nanostores/nanostores/issues/201
Notify always forced recomputing before. Now check fails when undefined is compared to out of range index.
Added existance check to diamond args to invalidate initial computation.

Fix computed with undefined argument

---

map/index.d.ts

These changes are needed to make the `build` method a standard for creating store builders.

types(map): extend `MapCreator`

---

README.md

I miss read this section over and over again. I read is as "special helpers to re-render the component on any store changes:" where the next code section is this special helper. However, this was referring to `useStore` which is documented way below in the specific framework section.
This should clarify this issue and make sure users look for "`useStore`" in the doc.

Readme: Clarify `useStore`

---

README.md

Reading the docs I noticed that the link to the Svelte documentation describing its store contract was no longer valid, this updates the link.

docs: update expired link to Svelte's store contract

---

computed/index.test.ts
deep-map/index.js

The problem was the lack of immutability as it works in `setKey()` of `map()`.

fix: missed recalculation of `computed` with `deepMap` inside it

---

README.md
deep-map/path.d.ts
deep-map/path.js
deep-map/path.test.ts
listen-keys/index.test.ts

Fixes https://github.com/nanostores/nanostores/issues/253
Added support for nested array access in path functions.
Added types of nested arrays in paths.
Updated deepMap example in README.
Added tests for setPath and setKey with nested arrays.

Add nested arrays support in path argument

---

README.md
computed/index.js
computed/index.test.ts
package.json

An idea that sprouted from the discussion here: https://github.com/orgs/nanostores/discussions/265.
When using computed values in listeners of the values they depend on the computed have stale values. This PR changes the priority of the value updates for computed values to be lower than the original atom without changing the priority of the listeners of the computed values.
(Sidenote: how are the functions included in the "All" size check decided? It's not including things like deepMap and listenKeys?)

feat!: Update computed values before other listeners

---

.github/workflows/release.yml
.github/workflows/test.yml

- Added release task after checking for push tags (release will be skipped if no notes are found for a tag in the CHANGELOG.md file).
- Added `contents: write` permissions to the workflow (required to create a release).
- Removed `--frozen-lockfile` as it is [automatically used](https://pnpm.io/next/cli/install#--frozen-lockfile) on CI. 
- Updated versions of actions used in workflow.

Releases on github #197

---

README.md
index.d.ts
index.js
listen-keys/index.d.ts
listen-keys/index.js
listen-keys/index.test.ts
package.json

Adds a subscribeKeys function. It ensures there's a `subscribe` function for every `listen` function, aligning the API for all types of store listeners. Also updated the readme to describe the listenKeys function
Fixes #262

feat: add subscribeKeys function

---

atom/index.d.ts
deep-map/index.d.ts
map/index.d.ts

Suggestion to re-add `notify()` to the public types following discussion in https://github.com/orgs/nanostores/discussions/276

Add notify() store method to public types

---

atom/index.d.ts

Noticed that I forgot to set the oldValue as optional in the atom notify method, only did it in the Map and DeepMap ones.

fix: oldValue in atom notify optional

---

atom/index.js
atom/index.test.ts
computed/index.test.ts
deep-map/index.test.ts
map/index.test.ts
package.json

Changes the behaviour of unsubscribe to also remove listeners that have already been queued.
It's a breaking change.
I remade the tests "does not mutate listeners while change event". Can't really work out what it was testing, and if/how I should replace it with something else.

feat!: does not run queued listeners after they are unsubscribed

---

computed/index.d.ts

Allow to use `batched` with `task`.
Little example:
```ts
const someStore1 = atom('test');
const someStore2 = atom('test');
const batchedStore = batched([someStore1, someStore2], () => {
return task(async () => {
return 'task';
});
});
batchedStore.subscribe(() => {});
setTimeout(() => {
// Throws type error
const value: string = batchedStore.get(); // Expected type 'string', got 'Task<string>'
});
```

Add missing `Task` type in `batch` types 

---

README.md
deep-map/index.js
deep-map/index.test.ts

To use `structuredClone` as part of the core, we would have to rewrite `notify`, which would add about 20 bytes to the `atom`, just to support `deepMap` mutability.
I think until we make `notify` a public API, it's better to use `structuredClone` only inside `deepMap`.

fix(deepMap): incorrect previous value when listening deep store

---

atom/index.js
computed/index.js
computed/index.test.ts
package.json

Fixes #299
This fixes stale values in computed stores by checking if dependencies have changed any time `get()` is called. It does have a perf impact, though I added an `epoch` optimization to help with that. And correctness should take precedence over performance (no other state library I'm aware of has this stale value problem). The benefits are:
- computed stores never return stale values
- this also solves the diamond problem, so the previous logic that was added for that is no longer needed, which means:
- simpler logic
- no need to store and compute a level (`l`) for each atom
- bundle size reduced (min: 286B to 235B, max:  818B to 769B)
- better perf in certain areas -- processing the `listenerQueue` is now O(n) instead of O(n^2)
Another potential benefit -- this change means that …

Fix stale computed values

---

atom/index.js
package.json

The new code in #380 needed to be updated to reflect the new lower number of items in listenerQueue per listener.

Fix merge of #300

---

atom/index.js
atom/index.test.ts
package.json

After switching to the `next` branch I discovered several issues introduced by #280:
- It was passing `index` instead of `queueIndex` to `listenerQueue.splice`. In addition to being the wrong index, this can put `listenerQueue` into a really weird/bad state when `index` is not divisible by 4 (since `listenerQueue` uses chunks of 4 items per listener).
- It was only removing the first listener it found in the queue, so it wouldn't work properly if the same listener was in the queue multiple times (e.g., when calling `set` on the same store multiple times inside a listener)
- It was removing items from the front of the queue, even if those items had already been processed. This would cause the next iteration of the queue processing loop to skip unprocessed items (because everything in the …

Fix issues with removing listeners from the queue

---

computed/index.js
package.json

The benchmark for `computed` on my machine increased from 3,815 ops/sec to 5,193 ops/sec

Improve computed perf by setting currentEpoch after set

---

deep-map/index.d.ts
deep-map/index.js
deep-map/index.test.ts
deep-map/path.d.ts
deep-map/path.js
deep-map/path.test.ts

Previously, calling `setKey` on a $deepMap would mutate the value in-place. This can cause various problems, for example #250 and #290. Those were both solved with workarounds, however, this solves it in a better way, by not mutating the deepMap in the first place.
Some advantages of this approach:
* No need for structuredClone
* The oldValue passed to listeners is the same object reference as the value that was previously passed. This is how immutable stores usually work, so it will align better with expectations, cause fewer issues, and allow for new use cases, like the upcoming batching PR which needs that behavior.
* Copies were already being made at each nesting level of the key being set, they just weren't being used (so maybe this was the original intent?). Either way, that means …

Don't mutate deepMap values

---

README.md
deep-map/index.d.ts
deep-map/path.d.ts

Fix docs mentioning structuredClone, no longer applies after #305

---

computed/index.js
computed/index.test.ts

Stripped out 14B.   The `currentRunId` is not really needed for tracking the stale state, since we already have `previousArgs` and `args`, which are sufficient.
I also covered staled behavior with test.

Decrease size of computed function

---

atom/errors.ts
atom/index.d.ts
computed/errors.ts
map/errors.ts
map/index.d.ts

This PR improves types for two things:
1. At the moment `atom.value` always includes `undefined` in its type, despite whether initial value was provided or not. So our test usually sprinkled with optional chaining operator (`?.`). This PR changes it and if initial value was specified in atom, then `atom.value` type will be inferred from it and won't have `undefined` in its type.
~~2. If you specify generic type in `map` method as `Record` then `setKey` method won't allow you pass `undefined` as the second parameter and therefore delete item from the map store. It fixes this.~~

Improve types

---

index.d.ts

This PR addresses an issue where type inference fails under the following TSconfig settings:
```json
{
"moduleResolution": "NodeNext",
"declaration": true
}
```
Since the implementation of #322, the new `Preinitialized` types were not being exported from the module root, causing the type inference to break.
A CodeSandbox example illustrating the issue can be found [here](https://codesandbox.io/p/sandbox/nanostores-typescript-issue-sx4kgm?file=%2Fsrc%2Fnanostores.ts).
**Changes in this PR:**
- Adds the missing exports for Preinitialized types to ensure proper type inference.

fix(TS): inferred type cannot be named without reference

---

README.md
effect/errors.ts
effect/index.d.ts
effect/index.js
effect/index.test.ts
index.d.ts
index.js

In spite of having ability to use atom's subscribe/notify methods for subscribing on changes, it might be a bit tricky to track changes at multiple atoms at once. `effect` is designed to solve this problem! And it is similar to the `effect` method from other state managers (like Solid's signals, or state manager in Svelte)
`effect` runs its callback on the start, with initial values, as well as on any store(s) change. If callback returns cleanup function it will be performed before next callback run. Besides that, `effect` returns own cleanup function, which allows cancelling the whole effect.
`effect` can be used as analogue of `subscribe` method on one store:
```ts
import { atom, effect } from 'nanostores'
const $num = atom(10)
effect($atom, num => {
console.log(`Number is ${num}`)
}) …
```

Add `effect` method

---

listen-keys/index.js

Avoid creating of the new array in the listenKeys function

---

listen-keys/index.d.ts

The typings for the subscribeKeys listener was missing the oldValue.
Fixes #348

fix(typescript): subscribeKeys listener missing oldValue

---

map/errors.ts
map/index.d.ts

The most asked question I've seen for this package is about the behavior of `setKey` on maps, when it comes to `undefined`. For string-indexed maps that don't explicitly allow undefined, users need to use type assertions to delete items. (For example, check out [this question](https://github.com/orgs/nanostores/discussions/353#discussioncomment-12338911)).
This behavior doesn’t really match how TypeScript handles string-indexed maps. While I think Nanostores current approach is technically more correct than TypeScript, it’s clearly not the behavior users expect (And it would break too many repos for TS to change it's default behavior, see [this discussion](https://github.com/microsoft/TypeScript/issues/49169)).
Therefore I came up with a solution where we can check if the Map is string …

Allow setKey undefined on string indexed maps

---

deep-map/errors.ts
deep-map/index.d.ts
deep-map/path.d.ts

Following up on #358, this PR adds typings for `deepMap`. I haven't used `deepMap`, so there might be some edge cases I've missed, but all of the changes are to the types.
The typings for the deep pathing is complicated, and it essentially forced me to duplicate the types that were affected. I also tried adding thorough type tests (Root level indexed, lower level indexed, making sure the base case was not affected), but if there are any cases that I didn't test I'd gladly add that.

Allow set key undefined on string indexed deepMap

---

map-creator/index.d.ts

I have updated the map-creator Record type to have a key of `number | string | symbol` instead of  `unknown`.
Why? When `skipLibCheck` is disabled (either set to false or not included at all), the TypeScript compiler will display the following:
> node_modules/nanostores/map-creator/index.d.ts:22:21 - error TS2344: Type 'unknown' does not satisfy
> the constraint 'string | number | symbol'.
> 
> 22   StoreExt = Record<unknown, any>

fix(map-creator): update the type for the record key

---

README.md

This PR updates the **Smart Stores** section of `README.md` by introducing a new entry:
> **Nanostores Immer** (`https://github.com/illuxiza/nanostores-immer`):
> A plugin that integrates [Immer](https://immerjs.github.io/immer/) with Nanostores, enabling immutable state updates via a familiar, mutable-style API.
- **README.md**
- Added a bullet under **Smart Stores** linking to the `nanostores-immer` repository.
- Briefly described its purpose and functionality.

Add Immer plugin to list of related projects in README
